apiVersion: v1
kind: Namespace
metadata:
  name: smart-scaler
  labels:
    project: k8s-smart-scaler
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    project: k8s-smart-scaler
